default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.5.0"
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: detect-private-key

  - repo: local

    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length=120, --target-version=py312]

      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [python]
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]

      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: system
        types: [python]
        args: [--py312-plus]

      - id: reorder-python-imports
        name: reorder-python-imports
        entry: reorder-python-imports
        language: system
        types: [python]
        args: [--py312-plus]

      - id: yesqa
        name: yesqa
        entry: yesqa
        language: system
        types: [python]

      - id: tests
        name: Run tests
        entry: "bash ./backend/.bin/tests.sh"
        language: system
        verbose: true
